import { describe, expect, test } from "bun:test";
import {
  assertMatePackagePaths,
  assertMateRuntimeCopyMode,
  assertMateRuntimeStampEmbedded,
  createMateStagedManifest,
  createMateThirdPartyNotices,
  createMateRuntimeStamp,
  generateMateRuntimeStampModule,
  MATE_PACKAGE_ALLOWLIST,
  pinnedBunLicenseBytes,
  serializeMateRuntimeStamp,
  stripMateBundleSourceNames,
} from "./mate-package-artifact.ts";
import type { StandaloneManifest } from "./standalone-assets.ts";

function standaloneManifest(): StandaloneManifest {
  return {
    schemaVersion: 1,
    artifact: "bb-mate",
    target: "bun-darwin-arm64",
    platform: "darwin",
    architecture: "arm64",
    mode: "0755",
    size: 64_783_586,
    sha256: "a".repeat(64),
    bunVersion: "1.3.14",
    runtimeVersion: "0.1.0-alpha.2",
    storyCount: 13,
    assets: [],
  };
}

describe("Mate package runtime artifact", () => {
  test("derives one deterministic embedded runtime stamp", () => {
    const stamp = createMateRuntimeStamp(standaloneManifest());

    expect(stamp).toEqual({
      schemaVersion: 1,
      artifact: "bb-mate",
      target: "bun-darwin-arm64",
      platform: "darwin",
      architecture: "arm64",
      mode: "0755",
      size: 64_783_586,
      sha256: "a".repeat(64),
      runtimeVersion: "0.1.0-alpha.2",
      expectedApiVersion: 1,
    });
    expect(serializeMateRuntimeStamp(stamp)).toBe(`${JSON.stringify(stamp)}\n`);
    expect(generateMateRuntimeStampModule(stamp)).toBe(
      [
        "// Generated by scripts/build-mate-package.ts. Do not edit.",
        "export const RUNTIME_ARTIFACT_STAMP = Object.freeze({",
        "  schemaVersion: 1,",
        '  artifact: "bb-mate",',
        '  target: "bun-darwin-arm64",',
        '  platform: "darwin",',
        '  architecture: "arm64",',
        '  mode: "0755",',
        "  size: 64783586,",
        `  sha256: "${"a".repeat(64)}",`,
        '  runtimeVersion: "0.1.0-alpha.2",',
        "  expectedApiVersion: 1,",
        "} as const);",
        "",
      ].join("\n"),
    );
  });

  test("accepts only the exact 14-file local-verification payload", () => {
    expect(MATE_PACKAGE_ALLOWLIST).toHaveLength(14);
    expect(MATE_PACKAGE_ALLOWLIST).toContain("BUN_LICENSE.md");
    expect(() => assertMatePackagePaths(MATE_PACKAGE_ALLOWLIST)).not.toThrow();
    expect(() =>
      assertMatePackagePaths([...MATE_PACKAGE_ALLOWLIST, "server.ts"]),
    ).toThrow("allowlist mismatch");
    expect(() =>
      assertMatePackagePaths(
        MATE_PACKAGE_ALLOWLIST.filter((file) => file !== "dist/app.js"),
      ),
    ).toThrow("allowlist mismatch");
    expect(() =>
      assertMatePackagePaths([
        ...MATE_PACKAGE_ALLOWLIST.filter(
          (file) => file !== "runtime/darwin-arm64/bb-mate",
        ),
        "runtime/darwin-arm64/../bb-mate",
      ]),
    ).toThrow("unsafe path");
  });

  test("rewrites the staged manifest to built public entrypoints", () => {
    const staged = createMateStagedManifest({
      name: "bb-plugin-mate",
      version: "0.1.0-alpha.1",
      private: true,
      type: "module",
      license: "MIT",
      engines: { bb: ">=0.36", bbPluginSdk: "^0.4.1" },
      bb: {
        name: "Plugin Workbench",
        description: "Develop source plugins.",
        branding: { icon: "Wrench" },
        server: "./server.ts",
        app: "./app.tsx",
        skills: ["./skills/plugin-workbench"],
      },
      files: ["source files are not trusted"],
      scripts: { build: "do not package" },
      devDependencies: { private: "workspace:*" },
    });

    expect(staged).toEqual({
      name: "bb-plugin-mate",
      version: "0.1.0-alpha.1",
      private: true,
      type: "module",
      license: "MIT",
      engines: { bb: ">=0.36", bbPluginSdk: "^0.4.1" },
      bb: {
        name: "Plugin Workbench",
        description: "Develop source plugins.",
        branding: { icon: "Wrench" },
        server: "./dist/server.js",
        app: "./dist/app.js",
        skills: ["./skills/plugin-workbench"],
      },
      files: MATE_PACKAGE_ALLOWLIST.filter((file) => file !== "package.json"),
    });
  });

  test("requires the exact runtime identity in the compiled backend", () => {
    const stamp = createMateRuntimeStamp(standaloneManifest());
    const compiled = [
      stamp.sha256,
      stamp.runtimeVersion,
      stamp.target,
      String(stamp.size),
      "expectedApiVersion:1",
    ].join(";");

    expect(() => assertMateRuntimeStampEmbedded(compiled, stamp)).not.toThrow();
    expect(() =>
      assertMateRuntimeStampEmbedded(
        compiled.replace(stamp.sha256, "b".repeat(64)),
        stamp,
      ),
    ).toThrow("does not embed the exact runtime stamp");
    expect(() =>
      assertMateRuntimeStampEmbedded(
        compiled.replace("expectedApiVersion:1", "expectedApiVersion:2"),
        stamp,
      ),
    ).toThrow("does not embed the exact runtime stamp");
  });

  test("requires copy to preserve the canonical executable mode", () => {
    expect(() => assertMateRuntimeCopyMode(0o755, 0o755)).not.toThrow();
    expect(() => assertMateRuntimeCopyMode(0o755, 0o644)).toThrow(
      "mode mismatch",
    );
    expect(() => assertMateRuntimeCopyMode(0o775, 0o775)).toThrow(
      "mode mismatch",
    );
  });

  test("adds explicit compiled-runtime coverage to package notices", () => {
    const notices = createMateThirdPartyNotices(
      "| zod | MIT | upstream |\n",
      "1.3.14",
    );
    expect(notices).toContain("bundled Zod protocol implementation");
    expect(notices).toContain(
      "compiled with and embeds the Bun 1.3.14 runtime",
    );
    expect(notices).toContain("Bun itself is MIT-licensed");
    expect(notices).toContain("JavaScriptCore and WebKit under LGPL-2");
    expect(notices).toContain("local verification only");
    expect(notices).toContain("BUN_LICENSE.md");
  });

  test("pins the exact upstream Bun license bytes", async () => {
    const source = await Bun.file(
      new URL("../plugins/mate/BUN_LICENSE.md", import.meta.url),
    ).bytes();
    const exact = pinnedBunLicenseBytes(source);
    expect(exact).toHaveLength(5_376);
    expect(exact.at(-1)).not.toBe(0x0a);
    expect(() =>
      pinnedBunLicenseBytes(Buffer.concat([exact, Buffer.from("\n")])),
    ).toThrow("pinned Bun 1.3.14");
    const pinned = Buffer.from("not the Bun license");
    expect(() => pinnedBunLicenseBytes(pinned)).toThrow("pinned Bun 1.3.14");
  });

  test("removes workspace source names without changing bundle code", () => {
    expect(
      stripMateBundleSourceNames(
        "// src/backend/plugin.ts\nconst ready=true;\n// ../../packages/runtime/src/protocol.ts\nready;\n//# sourceMappingURL=server.js.map\n",
      ),
    ).toBe("const ready=true;\nready;\n");
  });
});
