import { createHash } from "node:crypto";
import type { StandaloneManifest } from "./standalone-assets.ts";

export const PINNED_BUN_LICENSE_SHA256 =
  "2c6160ec8fb853f7e8f97d9b249e756c9b0ac44860a68b6bf4f1b0bcbc5c3741";

export const MATE_PACKAGE_ALLOWLIST = [
  "BUN_LICENSE.md",
  "LICENSE",
  "README.md",
  "THIRD_PARTY_LICENSES.md",
  "THIRD_PARTY_NOTICES.md",
  "dist/app.css",
  "dist/app.js",
  "dist/app.meta.json",
  "dist/server.js",
  "dist/server.meta.json",
  "package.json",
  "runtime/darwin-arm64/bb-mate",
  "runtime/darwin-arm64/manifest.json",
  "skills/plugin-workbench/SKILL.md",
] as const;

function compareText(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

export function assertMatePackagePaths(paths: readonly string[]): void {
  if (
    paths.some(
      (file) =>
        file.length === 0 ||
        file.startsWith("/") ||
        file.split(/[\\/]/u).some((part) => part === "" || part === ".."),
    )
  ) {
    throw new Error("Mate package contains an unsafe path.");
  }
  const actual = [...paths].sort(compareText);
  if (JSON.stringify(actual) !== JSON.stringify(MATE_PACKAGE_ALLOWLIST)) {
    throw new Error(`Mate package allowlist mismatch: ${actual.join(", ")}`);
  }
}

interface MateSourceManifest {
  readonly name: string;
  readonly version: string;
  readonly private: true;
  readonly type: string;
  readonly license: string;
  readonly engines: Record<string, unknown>;
  readonly bb: Record<string, unknown>;
  readonly files?: unknown;
  readonly scripts?: unknown;
  readonly devDependencies?: unknown;
}

export interface MateStagedManifest {
  readonly name: string;
  readonly version: string;
  readonly private: true;
  readonly type: string;
  readonly license: string;
  readonly engines: Record<string, unknown>;
  readonly bb: Record<string, unknown> & {
    readonly server: "./dist/server.js";
    readonly app: "./dist/app.js";
  };
  readonly files: readonly string[];
}

export function createMateStagedManifest(
  source: MateSourceManifest,
): MateStagedManifest {
  return {
    name: source.name,
    version: source.version,
    private: true,
    type: source.type,
    license: source.license,
    engines: source.engines,
    bb: {
      ...source.bb,
      server: "./dist/server.js",
      app: "./dist/app.js",
    },
    files: MATE_PACKAGE_ALLOWLIST.filter((file) => file !== "package.json"),
  };
}

export interface MateRuntimeStamp {
  schemaVersion: 1;
  artifact: "bb-mate";
  target: "bun-darwin-arm64";
  platform: "darwin";
  architecture: "arm64";
  mode: "0755";
  size: number;
  sha256: string;
  runtimeVersion: string;
  manifestSize: number;
  manifestSha256: string;
  expectedApiVersion: 2;
}

export function createMateRuntimeStamp(
  manifest: StandaloneManifest,
  manifestBytes: Uint8Array,
): MateRuntimeStamp {
  if (manifestBytes.byteLength < 2 || manifestBytes.byteLength > 1024 * 1024) {
    throw new Error("Standalone manifest bytes are outside the stamp bound.");
  }
  return {
    schemaVersion: 1,
    artifact: manifest.artifact,
    target: manifest.target,
    platform: manifest.platform,
    architecture: manifest.architecture,
    mode: manifest.mode,
    size: manifest.size,
    sha256: manifest.sha256,
    runtimeVersion: manifest.runtimeVersion,
    manifestSize: manifestBytes.byteLength,
    manifestSha256: createHash("sha256").update(manifestBytes).digest("hex"),
    expectedApiVersion: 2,
  };
}

export function serializeMateRuntimeStamp(stamp: MateRuntimeStamp): string {
  return `${JSON.stringify(stamp)}\n`;
}

export function generateMateRuntimeStampModule(
  stamp: MateRuntimeStamp,
): string {
  return [
    "// Generated by scripts/build-mate-package.ts. Do not edit.",
    "export const RUNTIME_ARTIFACT_STAMP = Object.freeze({",
    `  schemaVersion: ${stamp.schemaVersion},`,
    `  artifact: ${JSON.stringify(stamp.artifact)},`,
    `  target: ${JSON.stringify(stamp.target)},`,
    `  platform: ${JSON.stringify(stamp.platform)},`,
    `  architecture: ${JSON.stringify(stamp.architecture)},`,
    `  mode: ${JSON.stringify(stamp.mode)},`,
    `  size: ${stamp.size},`,
    `  sha256: ${JSON.stringify(stamp.sha256)},`,
    `  runtimeVersion: ${JSON.stringify(stamp.runtimeVersion)},`,
    `  manifestSize: ${stamp.manifestSize},`,
    `  manifestSha256: ${JSON.stringify(stamp.manifestSha256)},`,
    `  expectedApiVersion: ${stamp.expectedApiVersion},`,
    "} as const);",
    "",
  ].join("\n");
}

export function assertMateRuntimeStampEmbedded(
  compiledBackend: string,
  stamp: MateRuntimeStamp,
): void {
  const apiVersionPattern = new RegExp(
    `["']?expectedApiVersion["']?\\s*:\\s*${stamp.expectedApiVersion}(?:\\D|$)`,
    "u",
  );
  const exactValues = [
    stamp.sha256,
    stamp.runtimeVersion,
    stamp.target,
    String(stamp.size),
    String(stamp.manifestSize),
    stamp.manifestSha256,
  ];
  if (
    exactValues.some((value) => !compiledBackend.includes(value)) ||
    !apiVersionPattern.test(compiledBackend)
  ) {
    throw new Error(
      "Compiled Mate backend does not embed the exact runtime stamp.",
    );
  }
}

export function assertMateRuntimeCopyMode(
  sourceMode: number,
  stagedMode: number,
): void {
  if (sourceMode !== 0o755 || stagedMode !== sourceMode) {
    throw new Error(
      `Mate runtime mode mismatch: source=${sourceMode.toString(8)} staged=${stagedMode.toString(8)}.`,
    );
  }
}

export function createMateThirdPartyNotices(
  sourceNotices: string,
  bunVersion: string,
): string {
  return `${sourceNotices.trimEnd()}\n\n## Compiled runtime executable\n\nThe packaged bb-mate executable was compiled with and embeds the Bun ${bunVersion} runtime in addition to the bundled Zod protocol implementation listed above. Bun itself is MIT-licensed. Bun's pinned license identifies statically linked JavaScriptCore and WebKit under LGPL-2, tinycc under LGPL-2.1, and other linked components under the terms listed there. The exact upstream notice is included as BUN_LICENSE.md.\n\nThis package is for local verification only. It is not approved for upload, registry publication, release, or external redistribution pending a separate LGPL relink-material and complete third-party-license gate.\n`;
}

export function pinnedBunLicenseBytes(source: Uint8Array): Buffer {
  const exact = Buffer.from(source);
  if (
    createHash("sha256").update(exact).digest("hex") !==
    PINNED_BUN_LICENSE_SHA256
  ) {
    throw new Error("Bun license differs from the pinned Bun 1.3.14 bytes.");
  }
  return exact;
}

export function stripMateBundleSourceNames(bundle: string): string {
  return bundle
    .replace(/^\/\/ (?:src\/|\.\.\/\.\.\/packages\/)[^\r\n]*(?:\r?\n|$)/gmu, "")
    .replace(/^\/\/# sourceMappingURL=[^\r\n]*(?:\r?\n|$)/gmu, "");
}
