import { describe, expect, test } from "bun:test";
import {
  assertPluginStudioPackagePaths,
  assertPluginStudioRuntimeCopyMode,
  assertPluginStudioRuntimeStampEmbedded,
  createPluginStudioStagedManifest,
  createPluginStudioThirdPartyNotices,
  createPluginStudioRuntimeStamp,
  generatePluginStudioRuntimeStampModule,
  PLUGIN_STUDIO_PACKAGE_ALLOWLIST,
  pinnedBunLicenseBytes,
  serializePluginStudioRuntimeStamp,
  stripPluginStudioBundleSourceNames,
} from "./plugin-studio-package-artifact.ts";
import type { StandaloneManifest } from "./standalone-assets.ts";

function standaloneManifest(): StandaloneManifest {
  return {
    schemaVersion: 1,
    artifact: "bb-plugin-studio-runtime",
    target: "bun-darwin-arm64",
    platform: "darwin",
    architecture: "arm64",
    mode: "0755",
    size: 64_783_586,
    sha256: "a".repeat(64),
    bunVersion: "1.3.14",
    runtimeVersion: "0.1.0-alpha.3",
    storyCount: 13,
    assets: [],
  };
}

describe("Studio package runtime artifact", () => {
  test("derives one deterministic embedded runtime stamp", () => {
    const manifestBytes = Buffer.from('{"schemaVersion":1}\n');
    const stamp = createPluginStudioRuntimeStamp(
      standaloneManifest(),
      manifestBytes,
    );

    expect(stamp).toEqual({
      schemaVersion: 1,
      artifact: "bb-plugin-studio-runtime",
      target: "bun-darwin-arm64",
      platform: "darwin",
      architecture: "arm64",
      mode: "0755",
      size: 64_783_586,
      sha256: "a".repeat(64),
      runtimeVersion: "0.1.0-alpha.3",
      manifestSize: 20,
      manifestSha256:
        "80f3d90666804a9335821cdb40782458835ffedaef33088bd1dc5eb3ef85ce61",
      expectedApiVersion: 2,
    });
    expect(serializePluginStudioRuntimeStamp(stamp)).toBe(
      `${JSON.stringify(stamp)}\n`,
    );
    expect(generatePluginStudioRuntimeStampModule(stamp)).toBe(
      [
        "// Generated by scripts/build-plugin-studio-package.ts. Do not edit.",
        "export const RUNTIME_ARTIFACT_STAMP = Object.freeze({",
        "  schemaVersion: 1,",
        '  artifact: "bb-plugin-studio-runtime",',
        '  target: "bun-darwin-arm64",',
        '  platform: "darwin",',
        '  architecture: "arm64",',
        '  mode: "0755",',
        "  size: 64783586,",
        `  sha256: "${"a".repeat(64)}",`,
        '  runtimeVersion: "0.1.0-alpha.3",',
        "  manifestSize: 20,",
        '  manifestSha256: "80f3d90666804a9335821cdb40782458835ffedaef33088bd1dc5eb3ef85ce61",',
        "  expectedApiVersion: 2,",
        "} as const);",
        "",
      ].join("\n"),
    );
  });

  test("attests exact bounded manifest bytes including the trailing newline", () => {
    const manifest = standaloneManifest();
    const withNewline = createPluginStudioRuntimeStamp(
      manifest,
      Buffer.from('{"schemaVersion":1}\n'),
    );
    const withoutNewline = createPluginStudioRuntimeStamp(
      manifest,
      Buffer.from('{"schemaVersion":1}'),
    );

    expect(withNewline.manifestSize).toBe(withoutNewline.manifestSize + 1);
    expect(withNewline.manifestSha256).not.toBe(withoutNewline.manifestSha256);
    expect(() =>
      createPluginStudioRuntimeStamp(manifest, Buffer.alloc(1)),
    ).toThrow("outside the stamp bound");
    expect(() =>
      createPluginStudioRuntimeStamp(manifest, Buffer.alloc(1024 * 1024 + 1)),
    ).toThrow("outside the stamp bound");
  });

  test("accepts only the exact 15-file local-verification payload", () => {
    expect(PLUGIN_STUDIO_PACKAGE_ALLOWLIST).toHaveLength(15);
    expect(PLUGIN_STUDIO_PACKAGE_ALLOWLIST).toContain("BUN_LICENSE.md");
    expect(() =>
      assertPluginStudioPackagePaths(PLUGIN_STUDIO_PACKAGE_ALLOWLIST),
    ).not.toThrow();
    expect(() =>
      assertPluginStudioPackagePaths([
        ...PLUGIN_STUDIO_PACKAGE_ALLOWLIST,
        "server.ts",
      ]),
    ).toThrow("allowlist mismatch");
    expect(() =>
      assertPluginStudioPackagePaths(
        PLUGIN_STUDIO_PACKAGE_ALLOWLIST.filter(
          (file) => file !== "dist/app.js",
        ),
      ),
    ).toThrow("allowlist mismatch");
    expect(() =>
      assertPluginStudioPackagePaths([
        ...PLUGIN_STUDIO_PACKAGE_ALLOWLIST.filter(
          (file) => file !== "runtime/darwin-arm64/bb-plugin-studio-runtime",
        ),
        "runtime/darwin-arm64/../bb-plugin-studio-runtime",
      ]),
    ).toThrow("unsafe path");
  });

  test("rewrites the staged manifest to built public entrypoints", () => {
    const staged = createPluginStudioStagedManifest({
      name: "bb-plugin-studio",
      version: "0.1.0-alpha.2",
      description: "Build, inspect, and preview bb plugins.",
      homepage: "https://example.com",
      repository: { type: "git", url: "https://example.com/repo.git" },
      bugs: { url: "https://example.com/issues" },
      keywords: ["bb"],
      type: "module",
      license: "MIT",
      bin: { "bb-plugin-studio": "./dist/cli.js" },
      publishConfig: { access: "public", tag: "alpha" },
      engines: { bb: ">=0.36.0", bbPluginSdk: "^0.4.1" },
      bb: {
        name: "Plugin Studio",
        description: "Develop source plugins.",
        branding: { icon: "Toolbox" },
        server: "./server.ts",
        app: "./app.tsx",
        skills: ["./skills/plugin-studio"],
      },
      files: ["source files are not trusted"],
      scripts: { build: "do not package" },
      devDependencies: { private: "workspace:*" },
    });

    expect(staged).toEqual({
      name: "bb-plugin-studio",
      version: "0.1.0-alpha.2",
      description: "Build, inspect, and preview bb plugins.",
      homepage: "https://example.com",
      repository: { type: "git", url: "https://example.com/repo.git" },
      bugs: { url: "https://example.com/issues" },
      keywords: ["bb"],
      type: "module",
      license: "MIT",
      bin: { "bb-plugin-studio": "./dist/cli.js" },
      publishConfig: { access: "public", tag: "alpha" },
      engines: { bb: ">=0.36.0", bbPluginSdk: "^0.4.1" },
      bb: {
        name: "Plugin Studio",
        description: "Develop source plugins.",
        branding: { icon: "Toolbox" },
        server: "./dist/server.js",
        app: "./dist/app.js",
        skills: ["./skills/plugin-studio"],
      },
      files: PLUGIN_STUDIO_PACKAGE_ALLOWLIST.filter(
        (file) => file !== "package.json",
      ),
    });
  });

  test("requires the exact runtime identity in the compiled backend", () => {
    const stamp = createPluginStudioRuntimeStamp(
      standaloneManifest(),
      Buffer.from('{"schemaVersion":1}\n'),
    );
    const compiled = [
      stamp.sha256,
      stamp.runtimeVersion,
      stamp.target,
      String(stamp.size),
      String(stamp.manifestSize),
      stamp.manifestSha256,
      "expectedApiVersion:2",
    ].join(";");

    expect(() =>
      assertPluginStudioRuntimeStampEmbedded(compiled, stamp),
    ).not.toThrow();
    expect(() =>
      assertPluginStudioRuntimeStampEmbedded(
        compiled.replace(stamp.sha256, "b".repeat(64)),
        stamp,
      ),
    ).toThrow("does not embed the exact runtime stamp");
    expect(() =>
      assertPluginStudioRuntimeStampEmbedded(
        compiled.replace("expectedApiVersion:2", "expectedApiVersion:1"),
        stamp,
      ),
    ).toThrow("does not embed the exact runtime stamp");
    expect(() =>
      assertPluginStudioRuntimeStampEmbedded(
        compiled.replace(stamp.manifestSha256, "b".repeat(64)),
        stamp,
      ),
    ).toThrow("does not embed the exact runtime stamp");
  });

  test("requires copy to preserve the canonical executable mode", () => {
    expect(() => assertPluginStudioRuntimeCopyMode(0o755, 0o755)).not.toThrow();
    expect(() => assertPluginStudioRuntimeCopyMode(0o755, 0o644)).toThrow(
      "mode mismatch",
    );
    expect(() => assertPluginStudioRuntimeCopyMode(0o775, 0o775)).toThrow(
      "mode mismatch",
    );
  });

  test("adds explicit compiled-runtime coverage to package notices", () => {
    const notices = createPluginStudioThirdPartyNotices(
      "| zod | MIT | upstream |\n",
      "1.3.14",
    );
    expect(notices).toContain("bundled Zod protocol implementation");
    expect(notices).toContain(
      "compiled with and embeds the Bun 1.3.14 runtime",
    );
    expect(notices).toContain("Bun itself is MIT-licensed");
    expect(notices).toContain("JavaScriptCore and WebKit under LGPL-2");
    expect(notices).toContain("local verification only");
    expect(notices).toContain("BUN_LICENSE.md");
  });

  test("pins the exact upstream Bun license bytes", async () => {
    const source = await Bun.file(
      new URL("../plugins/studio/BUN_LICENSE.md", import.meta.url),
    ).bytes();
    const exact = pinnedBunLicenseBytes(source);
    expect(exact).toHaveLength(5_376);
    expect(exact.at(-1)).not.toBe(0x0a);
    expect(() =>
      pinnedBunLicenseBytes(Buffer.concat([exact, Buffer.from("\n")])),
    ).toThrow("pinned Bun 1.3.14");
    const pinned = Buffer.from("not the Bun license");
    expect(() => pinnedBunLicenseBytes(pinned)).toThrow("pinned Bun 1.3.14");
  });

  test("removes workspace source names without changing bundle code", () => {
    expect(
      stripPluginStudioBundleSourceNames(
        "// src/backend/plugin.ts\nconst ready=true;\n// ../../packages/runtime/src/protocol.ts\nready;\n//# sourceMappingURL=server.js.map\n",
      ),
    ).toBe("const ready=true;\nready;\n");
  });
});
