import {
  DEVELOPMENT_TARGET_EVENT_RETENTION_MIGRATION_SQL,
  DEVELOPMENT_TARGET_HOST_MIGRATION_SQL,
  DEVELOPMENT_TARGET_MIGRATIONS,
  DEVELOPMENT_TARGET_PROJECT_SCOPE_BACKFILL_MIGRATION_SQL,
  DEVELOPMENT_TARGET_PROJECT_SCOPE_MIGRATION_SQL,
  DEVELOPMENT_TARGET_RETENTION_GUARD_MIGRATION_SQL,
  DEVELOPMENT_TARGET_RETIREMENT_MIGRATION_SQL,
  DEVELOPMENT_TARGET_SOURCE_MIGRATION_SQL,
} from "../discovery/schema.ts";
import { EVENT_MIGRATION_SQL, EVENT_MIGRATIONS } from "../events/schema.ts";
import type { RuntimeMigration } from "./migrations.ts";
import { OBJECT_MIGRATION_SQL, OBJECT_MIGRATIONS } from "./schema.ts";
import type { SqliteDatabase } from "./sqlite.ts";

export const DEVELOPMENT_TARGET_CATALOG_MIGRATION_STATEMENTS = Object.freeze([
  OBJECT_MIGRATION_SQL,
  EVENT_MIGRATION_SQL,
  DEVELOPMENT_TARGET_SOURCE_MIGRATION_SQL,
  DEVELOPMENT_TARGET_HOST_MIGRATION_SQL,
  DEVELOPMENT_TARGET_RETIREMENT_MIGRATION_SQL,
  DEVELOPMENT_TARGET_RETENTION_GUARD_MIGRATION_SQL,
  DEVELOPMENT_TARGET_PROJECT_SCOPE_MIGRATION_SQL,
  DEVELOPMENT_TARGET_EVENT_RETENTION_MIGRATION_SQL,
  DEVELOPMENT_TARGET_PROJECT_SCOPE_BACKFILL_MIGRATION_SQL,
] as const);

export const RUNTIME_MIGRATIONS: readonly RuntimeMigration[] = [
  ...OBJECT_MIGRATIONS,
  ...EVENT_MIGRATIONS,
  ...DEVELOPMENT_TARGET_MIGRATIONS,
];

export function verifyDevelopmentTargetCatalogSchema(
  database: SqliteDatabase,
): void {
  for (const migration of RUNTIME_MIGRATIONS) migration.verify?.(database);
}
